name: Hello World

on: push

jobs:
    my-jobs:
        name: Print Hello World
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello World
              run: echo "Hello World"
            - name: Print Name
              run: echo "Rajeshs"
     



